default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['SUPABASE_DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['SUPABASE_DATABASE_URL_TEST'] %>

staging:
  <<: *default
  url: <%= ENV['SUPABASE_DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['SUPABASE_DATABASE_URL'] %>